AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: S26 SmartGallery Backend

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              Access-Control-Allow-Methods: "'GET,POST,OPTIONS,PUT,PATCH,DELETE'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              Access-Control-Allow-Methods: "'GET,POST,OPTIONS,PUT,PATCH,DELETE'"
      Cors:
        AllowMethods: "'GET,POST,OPTIONS,PUT,PATCH,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToOptions: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn
            Identity:
              Header: Authorization

  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          BUCKET_NAME: !Ref BucketName
          GSI_NAME: !Ref GSIName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
        - S3CrudPolicy:
            BucketName: !Ref BucketName
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: get
            RestApiId: !Ref ServerlessRestApi
        ListImages:
          Type: Api
          Properties:
            Path: /images
            Method: get
            RestApiId: !Ref ServerlessRestApi
        ListImagesOptions:
          Type: Api
          Properties:
            Path: /images
            Method: options
            RestApiId: !Ref ServerlessRestApi
        GetImageMetadata:
          Type: Api
          Properties:
            Path: /images/{imageId}
            Method: get
            RestApiId: !Ref ServerlessRestApi
        GetImageMetadataOptions:
          Type: Api
          Properties:
            Path: /images/{imageId}
            Method: options
            RestApiId: !Ref ServerlessRestApi
        UploadImage:
          Type: Api
          Properties:
            Path: /upload
            Method: post
            RestApiId: !Ref ServerlessRestApi
        UploadOptions:
          Type: Api
          Properties:
            Path: /upload
            Method: options
            RestApiId: !Ref ServerlessRestApi
        UpdateImage:
          Type: Api
          Properties:
            Path: /update-metadata
            Method: patch
            RestApiId: !Ref ServerlessRestApi
        UpdateMetadataOptions:
          Type: Api
          Properties:
            Path: /update-metadata
            Method: options
            RestApiId: !Ref ServerlessRestApi
        DeleteImage:
          Type: Api
          Properties:
            Path: /image/{image_id}
            Method: delete
            RestApiId: !Ref ServerlessRestApi
        DeleteImageOptions:
          Type: Api
          Properties:
            Path: /image/{image_id}
            Method: options
            RestApiId: !Ref ServerlessRestApi

  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/processor.lambda_handler
      Runtime: python3.13
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          BUCKET_NAME: !Ref BucketName
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName
        - DynamoDBWritePolicy:
            TableName: !Ref TableName
        - RekognitionDetectOnlyPolicy: {}

  AllowS3ToInvokeProcessor:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref ImageProcessorFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${BucketName}"

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"

Parameters:
  TableName:
    Type: String
  BucketName:
    Type: String
  GSIName:
    Type: String
    Default: userId-uploadedAt-index
  UserPoolArn:
    Type: String
    Default: "arn:aws:cognito-idp:us-east-1:357938784666:userpool/us-east-1_370bciKRJ"

Outputs:
  BackendApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  BackendFunction:
    Value: !GetAtt BackendFunction.Arn
  ImageBucketName:
    Value: !Ref BucketName
  ImageMetadataTableName:
    Value: !Ref TableName